name: Upload Website

# This file was made by lord of the cat - meow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      envFile:
        description: Env file to deploy
        type: string
        required: false
        default: '.env.production'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node
        run: |
          sudo apt update
          curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
          sudo apt -y install nodejs
      - name: Build Artifact
        run: |
          if [ -z "${{inputs.envFile}}" ] 
          then 
          ENV=.env.production
          else 
          ENV=${{inputs.envFile}}
          fi
          export NODE_OPTIONS=--openssl-legacy-provider && npm install --legacy-peer-deps && \
          npm i -g env-cmd && \
          export NODE_OPTIONS=--openssl-legacy-provider && CI=false env-cmd -f ${ENV} npm run build
          cp ${{ github.workspace }}/cfg/web.config ${{ github.workspace }}/build/
      - name: Zip Package
        run: |
          cd ${{ github.workspace }}/build
          zip -r ${{ github.workspace }}/build.zip *
      - name: Upload zip sources
        uses: actions/upload-artifact@v2
        with:
          name: pos-system-frontend
          path: build.zip
  Deploy:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Clone source zip
        uses: actions/download-artifact@v2
        with:
          name: pos-system-frontend
      - name: Deploy to IIS
        shell: powershell
        run: |
          iisreset /stop
          Remove-Item -Recurse -Force -Confirm:$false D:\web-frontend\
          mkdir D:\web-frontend
          Expand-Archive build.zip D:\web-frontend
          iisreset /start
